---
- name: Configure network and SSH key
  hosts: all
  become: true

  vars:
  public_interface: eth0
  internal_interface: eth1
  public_ip: "10.10.24.5"
  internal_ip: "34.56.125.14"

  new_username: "OCHYRKA"

  vars_files:
    - defaults/main.yml
  tasks:
    - include_tasks: tasks/configure_routes.yml
    - include_tasks: tasks/create_user_gen_sshkey.yml
    - include_tasks: tasks/restrict_ssh.yml
    - include_tasks: tasks/configure_firewalld.yml
