---
- name: Define variables
  set_fact:
    generate_user: true
    ssh_user: "{{ new_username | default(default_ssh_user) }}"

- name: Create a new user if required
  user:
    name: new_ssh_user
    state: "{{ 'present' if generate_user else 'absent' }}"
    shell: /bin/bash
  when: generate_user | default(false)
- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: 0700

- name: Generate SSH key
  command:
    cmd: "ssh-keygen -t rsa -b 4096 -f /home/{{ ssh_user }}/.ssh/id_rsa -N ''"
    creates: "/home/{{ ssh_user }}/.ssh/id_rsa"
  become_user: "{{ ssh_user }}"

- name: Display public SSH key
  shell: cat /home/{{ ssh_user }}/.ssh/id_rsa.pub
  register: ssh_key
  become_user: "{{ ssh_user }}"

- name: Show generated SSH key
  debug:
    msg: "Generated SSH key for {{ ssh_user }}: {{ ssh_key.stdout }}"
